Adicionando o Azure
claudioviniciuso/storage-tool pull request #7
Opened 2023-12-03 03:00 UTC by mhadaniya

:construction: Vou criar esse PR como draft ainda!

@claudioviniciuso Se vc puder dar uma olhada depois e indicar o que mais precisa em relação aos métodos, se precisa adicionar algum tratamento de exceção a mais ou alterar o retorno de algum método, só indicar. Se preferir, pode deixar como comentário no próprio review aqui ou mandar mensagem. 

Agora vou finalizar os testes unitários (como acabei usando o arquivo `azure_example.py` para os testes, vai ficar mais fácil) e a documentação amanhã de noite (03/12), se alguma correção que vc aponte também. Estava pensando em criar uma pasta `docs\azure` e documentar lá.

2023-12-03 15:22 UTC, claudioviniciuso requested changes
OK!

2023-12-03 15:22 UTC, claudioviniciuso commented on storage_tool/azure.py
> +            for container in containers:
Retirar print. Isso polui um pouco o Log do Airlfow.

2023-12-04 04:31 UTC, mhadaniya commented on .env.testing
> +AZURE_STORAGE_CONNECTION_STRING='DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEnd
Essa daqui não é a minha chave, é do [Azurite](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio) para executar os testes unitários. Mas se por bem achar melhor, posso remover também.

2023-12-04 04:34 UTC, mhadaniya commented on tests/test_azure.py
Pra executar esses testes localmente, eu fiz usando o [Azurite](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio-code#install-azurite). Tem as suas limitações, por exemplo, não consegui criar containers diferentes, e vem 2 por padrão. Mas de resto, consegui testar tudo.

2023-12-04 09:29 UTC, claudioviniciuso approved these changes

2023-12-04 09:29 UTC, claudioviniciuso commented on .env.testing
> +AZURE_STORAGE_CONNECTION_STRING='DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEnd
OK

2023-12-04 09:30 UTC, merged